name: Check and patch Obsidian Android edition.
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  check-and-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python requests Lib
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Save keystore file
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore

      - name: Run action.py
        run: |
          wget -O action.py https://github.com/YuanWeiSite/Obsidian-Android-Patch/raw/refs/heads/main/action.py
          python action.py ${{ secrets.REPO_TOKEN }}
